// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: options/preprocess.proto

/*
Package preprocess is a generated protocol buffer package.

It is generated from these files:
	options/preprocess.proto

It has these top-level messages:
	PreprocessMessageOptions
	PreprocessFieldOptions
	PreprocessString
*/
package preprocess

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/gogo/protobuf/protoc-gen-gogo/descriptor"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type PreprocessString_Methods int32

const (
	PreprocessString_none       PreprocessString_Methods = 0
	PreprocessString_trim_space PreprocessString_Methods = 1
	PreprocessString_upper      PreprocessString_Methods = 2
	PreprocessString_lower      PreprocessString_Methods = 3
)

var PreprocessString_Methods_name = map[int32]string{
	0: "none",
	1: "trim_space",
	2: "upper",
	3: "lower",
}
var PreprocessString_Methods_value = map[string]int32{
	"none":       0,
	"trim_space": 1,
	"upper":      2,
	"lower":      3,
}

func (x PreprocessString_Methods) String() string {
	return proto.EnumName(PreprocessString_Methods_name, int32(x))
}
func (PreprocessString_Methods) EnumDescriptor() ([]byte, []int) {
	return fileDescriptorPreprocess, []int{2, 0}
}

type PreprocessMessageOptions struct {
	String_ *PreprocessString `protobuf:"bytes,1,opt,name=string" json:"string,omitempty"`
}

func (m *PreprocessMessageOptions) Reset()         { *m = PreprocessMessageOptions{} }
func (m *PreprocessMessageOptions) String() string { return proto.CompactTextString(m) }
func (*PreprocessMessageOptions) ProtoMessage()    {}
func (*PreprocessMessageOptions) Descriptor() ([]byte, []int) {
	return fileDescriptorPreprocess, []int{0}
}

func (m *PreprocessMessageOptions) GetString_() *PreprocessString {
	if m != nil {
		return m.String_
	}
	return nil
}

type PreprocessFieldOptions struct {
	String_ *PreprocessString `protobuf:"bytes,1,opt,name=string" json:"string,omitempty"`
}

func (m *PreprocessFieldOptions) Reset()                    { *m = PreprocessFieldOptions{} }
func (m *PreprocessFieldOptions) String() string            { return proto.CompactTextString(m) }
func (*PreprocessFieldOptions) ProtoMessage()               {}
func (*PreprocessFieldOptions) Descriptor() ([]byte, []int) { return fileDescriptorPreprocess, []int{1} }

func (m *PreprocessFieldOptions) GetString_() *PreprocessString {
	if m != nil {
		return m.String_
	}
	return nil
}

type PreprocessString struct {
	Methods []PreprocessString_Methods `protobuf:"varint,1,rep,packed,name=methods,enum=preprocess.PreprocessString_Methods" json:"methods,omitempty"`
}

func (m *PreprocessString) Reset()                    { *m = PreprocessString{} }
func (m *PreprocessString) String() string            { return proto.CompactTextString(m) }
func (*PreprocessString) ProtoMessage()               {}
func (*PreprocessString) Descriptor() ([]byte, []int) { return fileDescriptorPreprocess, []int{2} }

func (m *PreprocessString) GetMethods() []PreprocessString_Methods {
	if m != nil {
		return m.Methods
	}
	return nil
}

var E_Each = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.MessageOptions)(nil),
	ExtensionType: (*PreprocessMessageOptions)(nil),
	Field:         11111,
	Name:          "preprocess.each",
	Tag:           "bytes,11111,opt,name=each",
	Filename:      "options/preprocess.proto",
}

var E_Field = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.FieldOptions)(nil),
	ExtensionType: (*PreprocessFieldOptions)(nil),
	Field:         11111,
	Name:          "preprocess.field",
	Tag:           "bytes,11111,opt,name=field",
	Filename:      "options/preprocess.proto",
}

func init() {
	proto.RegisterType((*PreprocessMessageOptions)(nil), "preprocess.PreprocessMessageOptions")
	proto.RegisterType((*PreprocessFieldOptions)(nil), "preprocess.PreprocessFieldOptions")
	proto.RegisterType((*PreprocessString)(nil), "preprocess.PreprocessString")
	proto.RegisterEnum("preprocess.PreprocessString_Methods", PreprocessString_Methods_name, PreprocessString_Methods_value)
	proto.RegisterExtension(E_Each)
	proto.RegisterExtension(E_Field)
}

func init() { proto.RegisterFile("options/preprocess.proto", fileDescriptorPreprocess) }

var fileDescriptorPreprocess = []byte{
	// 292 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x92, 0x4d, 0x4b, 0xc3, 0x40,
	0x10, 0x86, 0x8d, 0xfd, 0xd2, 0x51, 0x4a, 0xd8, 0x83, 0x04, 0x51, 0x0c, 0xc1, 0x43, 0x4f, 0x1b,
	0xa8, 0x5e, 0xec, 0xc1, 0x83, 0x07, 0x6f, 0xd5, 0x12, 0x41, 0xa4, 0x17, 0x49, 0x93, 0x69, 0x1a,
	0x48, 0x33, 0xcb, 0xee, 0x16, 0x7f, 0x85, 0xbf, 0xd3, 0xbf, 0x21, 0xdd, 0x6d, 0x4c, 0xea, 0xd7,
	0xa5, 0xb7, 0x30, 0xef, 0x33, 0x4f, 0x76, 0x5f, 0x16, 0x3c, 0x12, 0x3a, 0xa7, 0x52, 0x85, 0x42,
	0xa2, 0x90, 0x94, 0xa0, 0x52, 0x5c, 0x48, 0xd2, 0xc4, 0xa0, 0x9e, 0x9c, 0xfa, 0x19, 0x51, 0x56,
	0x60, 0x68, 0x92, 0xd9, 0x6a, 0x1e, 0xa6, 0xa8, 0x12, 0x99, 0x0b, 0x4d, 0xd2, 0xd2, 0xc1, 0x04,
	0xbc, 0xc9, 0x17, 0x3f, 0x46, 0xa5, 0xe2, 0x0c, 0x1f, 0xad, 0x9a, 0x5d, 0x43, 0x57, 0x69, 0x99,
	0x97, 0x99, 0xe7, 0xf8, 0xce, 0xe0, 0x68, 0x78, 0xc6, 0x1b, 0x3f, 0xab, 0xb7, 0x9e, 0x0c, 0x13,
	0x6d, 0xd8, 0xe0, 0x01, 0x4e, 0xea, 0xec, 0x3e, 0xc7, 0x22, 0xdd, 0xcd, 0xf7, 0xee, 0x80, 0xfb,
	0x3d, 0x64, 0xb7, 0xd0, 0x5b, 0xa2, 0x5e, 0x50, 0xaa, 0x3c, 0xc7, 0x6f, 0x0d, 0xfa, 0xc3, 0xcb,
	0xff, 0x5c, 0x7c, 0x6c, 0xd9, 0xa8, 0x5a, 0x0a, 0x6e, 0xa0, 0xb7, 0x99, 0xb1, 0x03, 0x68, 0x97,
	0x54, 0xa2, 0xbb, 0xc7, 0xfa, 0x00, 0x5a, 0xe6, 0xcb, 0x57, 0x25, 0xe2, 0x04, 0x5d, 0x87, 0x1d,
	0x42, 0x67, 0x25, 0x04, 0x4a, 0x77, 0x7f, 0xfd, 0x59, 0xd0, 0x1b, 0x4a, 0xb7, 0x35, 0x9a, 0x42,
	0x1b, 0xe3, 0x64, 0xc1, 0x2e, 0xb8, 0x2d, 0x97, 0x57, 0xe5, 0xf2, 0xed, 0xfa, 0xbc, 0x8f, 0x67,
	0x73, 0xcb, 0x3f, 0x4e, 0xb6, 0x0d, 0x47, 0xc6, 0x39, 0x7a, 0x81, 0xce, 0x7c, 0xdd, 0x18, 0x3b,
	0xff, 0x21, 0x6f, 0x36, 0x59, 0xa9, 0x83, 0xdf, 0xd5, 0x4d, 0x34, 0xb2, 0xc2, 0xbb, 0xe3, 0x69,
	0xe3, 0x5d, 0xcc, 0xba, 0x46, 0x7b, 0xf5, 0x19, 0x00, 0x00, 0xff, 0xff, 0x28, 0xba, 0x8d, 0x2a,
	0x46, 0x02, 0x00, 0x00,
}
