// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: github.com/infobloxopen/protoc-gen-preprocess/options/preprocess.proto

/*
Package preprocess is a generated protocol buffer package.

It is generated from these files:
	github.com/infobloxopen/protoc-gen-preprocess/options/preprocess.proto

It has these top-level messages:
	PreprocessMessageOptions
	PreprocessFieldOptions
	PreprocessString
*/
package preprocess

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/gogo/protobuf/protoc-gen-gogo/descriptor"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type PreprocessString_Methods int32

const (
	PreprocessString_none  PreprocessString_Methods = 0
	PreprocessString_trim  PreprocessString_Methods = 1
	PreprocessString_upper PreprocessString_Methods = 2
	PreprocessString_lower PreprocessString_Methods = 3
	PreprocessString_clear PreprocessString_Methods = 4
)

var PreprocessString_Methods_name = map[int32]string{
	0: "none",
	1: "trim",
	2: "upper",
	3: "lower",
	4: "clear",
}
var PreprocessString_Methods_value = map[string]int32{
	"none":  0,
	"trim":  1,
	"upper": 2,
	"lower": 3,
	"clear": 4,
}

func (x PreprocessString_Methods) String() string {
	return proto.EnumName(PreprocessString_Methods_name, int32(x))
}
func (PreprocessString_Methods) EnumDescriptor() ([]byte, []int) {
	return fileDescriptorPreprocess, []int{2, 0}
}

type PreprocessMessageOptions struct {
	String_ *PreprocessString `protobuf:"bytes,1,opt,name=string" json:"string,omitempty"`
}

func (m *PreprocessMessageOptions) Reset()         { *m = PreprocessMessageOptions{} }
func (m *PreprocessMessageOptions) String() string { return proto.CompactTextString(m) }
func (*PreprocessMessageOptions) ProtoMessage()    {}
func (*PreprocessMessageOptions) Descriptor() ([]byte, []int) {
	return fileDescriptorPreprocess, []int{0}
}

func (m *PreprocessMessageOptions) GetString_() *PreprocessString {
	if m != nil {
		return m.String_
	}
	return nil
}

type PreprocessFieldOptions struct {
	String_ *PreprocessString `protobuf:"bytes,1,opt,name=string" json:"string,omitempty"`
}

func (m *PreprocessFieldOptions) Reset()                    { *m = PreprocessFieldOptions{} }
func (m *PreprocessFieldOptions) String() string            { return proto.CompactTextString(m) }
func (*PreprocessFieldOptions) ProtoMessage()               {}
func (*PreprocessFieldOptions) Descriptor() ([]byte, []int) { return fileDescriptorPreprocess, []int{1} }

func (m *PreprocessFieldOptions) GetString_() *PreprocessString {
	if m != nil {
		return m.String_
	}
	return nil
}

type PreprocessString struct {
	Methods []PreprocessString_Methods `protobuf:"varint,1,rep,packed,name=methods,enum=preprocess.PreprocessString_Methods" json:"methods,omitempty"`
}

func (m *PreprocessString) Reset()                    { *m = PreprocessString{} }
func (m *PreprocessString) String() string            { return proto.CompactTextString(m) }
func (*PreprocessString) ProtoMessage()               {}
func (*PreprocessString) Descriptor() ([]byte, []int) { return fileDescriptorPreprocess, []int{2} }

func (m *PreprocessString) GetMethods() []PreprocessString_Methods {
	if m != nil {
		return m.Methods
	}
	return nil
}

var E_Each = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.MessageOptions)(nil),
	ExtensionType: (*PreprocessMessageOptions)(nil),
	Field:         11111,
	Name:          "preprocess.each",
	Tag:           "bytes,11111,opt,name=each",
	Filename:      "github.com/infobloxopen/protoc-gen-preprocess/options/preprocess.proto",
}

var E_Field = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.FieldOptions)(nil),
	ExtensionType: (*PreprocessFieldOptions)(nil),
	Field:         11111,
	Name:          "preprocess.field",
	Tag:           "bytes,11111,opt,name=field",
	Filename:      "github.com/infobloxopen/protoc-gen-preprocess/options/preprocess.proto",
}

func init() {
	proto.RegisterType((*PreprocessMessageOptions)(nil), "preprocess.PreprocessMessageOptions")
	proto.RegisterType((*PreprocessFieldOptions)(nil), "preprocess.PreprocessFieldOptions")
	proto.RegisterType((*PreprocessString)(nil), "preprocess.PreprocessString")
	proto.RegisterEnum("preprocess.PreprocessString_Methods", PreprocessString_Methods_name, PreprocessString_Methods_value)
	proto.RegisterExtension(E_Each)
	proto.RegisterExtension(E_Field)
}

func init() {
	proto.RegisterFile("github.com/infobloxopen/protoc-gen-preprocess/options/preprocess.proto", fileDescriptorPreprocess)
}

var fileDescriptorPreprocess = []byte{
	// 320 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x92, 0x3d, 0x4f, 0xf3, 0x30,
	0x10, 0xc7, 0x9f, 0x3c, 0x7d, 0x83, 0x03, 0xa1, 0xc8, 0x03, 0x8a, 0x10, 0x88, 0x2a, 0x62, 0xe8,
	0x52, 0x47, 0x2a, 0x4c, 0x1d, 0x3a, 0x30, 0x74, 0x2b, 0x54, 0x41, 0x42, 0xa8, 0x5b, 0x93, 0x5e,
	0x53, 0x4b, 0xa9, 0xcf, 0xb2, 0x5d, 0xc1, 0xe7, 0xe0, 0x4b, 0xf2, 0x35, 0x50, 0xe2, 0x96, 0xa4,
	0xbc, 0x2d, 0x6c, 0xa7, 0xbb, 0xdf, 0xfd, 0x6c, 0xff, 0x65, 0x18, 0x67, 0xc2, 0xae, 0x36, 0x09,
	0x4f, 0x69, 0x1d, 0x09, 0xb9, 0xa4, 0x24, 0xa7, 0x17, 0x52, 0x28, 0x23, 0xa5, 0xc9, 0x52, 0xda,
	0xcf, 0x50, 0xf6, 0x95, 0x46, 0xa5, 0x29, 0x45, 0x63, 0x22, 0x52, 0x56, 0x90, 0x34, 0x51, 0xd5,
	0xe2, 0x25, 0xc8, 0xa0, 0xea, 0x9c, 0x75, 0x33, 0xa2, 0x2c, 0x47, 0xa7, 0x48, 0x36, 0xcb, 0x68,
	0x81, 0x26, 0xd5, 0x42, 0x59, 0xd2, 0x8e, 0x0e, 0xa7, 0x10, 0x4c, 0x3f, 0xf8, 0x09, 0x1a, 0x33,
	0xcf, 0xf0, 0xde, 0xa9, 0xd9, 0x0d, 0xb4, 0x8d, 0xd5, 0x42, 0x66, 0x81, 0xd7, 0xf5, 0x7a, 0x47,
	0x83, 0x73, 0x5e, 0x3b, 0xac, 0xda, 0x7a, 0x28, 0x99, 0x78, 0xcb, 0x86, 0x77, 0x70, 0x5a, 0xcd,
	0xc6, 0x02, 0xf3, 0xc5, 0xdf, 0x7c, 0xaf, 0x1e, 0xf8, 0x9f, 0x87, 0x6c, 0x04, 0x9d, 0x35, 0xda,
	0x15, 0x2d, 0x4c, 0xe0, 0x75, 0x1b, 0xbd, 0x93, 0xc1, 0xd5, 0x6f, 0x2e, 0x3e, 0x71, 0x6c, 0xbc,
	0x5b, 0x0a, 0x47, 0xd0, 0xd9, 0xf6, 0xd8, 0x01, 0x34, 0x25, 0x49, 0xf4, 0xff, 0x15, 0x95, 0xd5,
	0x62, 0xed, 0x7b, 0xec, 0x10, 0x5a, 0x1b, 0xa5, 0x50, 0xfb, 0xff, 0x8b, 0x32, 0xa7, 0x67, 0xd4,
	0x7e, 0xa3, 0x28, 0xd3, 0x1c, 0xe7, 0xda, 0x6f, 0x0e, 0x67, 0xd0, 0xc4, 0x79, 0xba, 0x62, 0x97,
	0xdc, 0x25, 0xcc, 0x77, 0x09, 0xf3, 0xfd, 0x0c, 0x83, 0xb7, 0xc7, 0xf2, 0xa9, 0x3f, 0x5c, 0x6f,
	0x1f, 0x8e, 0x4b, 0xe7, 0xf0, 0x09, 0x5a, 0xcb, 0x22, 0x36, 0x76, 0xf1, 0x45, 0x5e, 0x8f, 0x73,
	0xa7, 0x0e, 0xbf, 0x57, 0xd7, 0xd1, 0xd8, 0x09, 0x6f, 0x8f, 0x67, 0xb5, 0xcf, 0x91, 0xb4, 0x4b,
	0xed, 0xf5, 0x7b, 0x00, 0x00, 0x00, 0xff, 0xff, 0xf4, 0xbc, 0x55, 0x4a, 0x79, 0x02, 0x00, 0x00,
}
