// Code generated by protoc-gen-go. DO NOT EDIT.
// source: demo.proto

package demo

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/atorgayev/protoc-gen-preprocess/options"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Demo struct {
	S                    string   `protobuf:"bytes,1,opt,name=s,proto3" json:"s,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Demo) Reset()         { *m = Demo{} }
func (m *Demo) String() string { return proto.CompactTextString(m) }
func (*Demo) ProtoMessage()    {}
func (*Demo) Descriptor() ([]byte, []int) {
	return fileDescriptor_demo_6f9e178caa5c9b6a, []int{0}
}
func (m *Demo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Demo.Unmarshal(m, b)
}
func (m *Demo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Demo.Marshal(b, m, deterministic)
}
func (dst *Demo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Demo.Merge(dst, src)
}
func (m *Demo) XXX_Size() int {
	return xxx_messageInfo_Demo.Size(m)
}
func (m *Demo) XXX_DiscardUnknown() {
	xxx_messageInfo_Demo.DiscardUnknown(m)
}

var xxx_messageInfo_Demo proto.InternalMessageInfo

func (m *Demo) GetS() string {
	if m != nil {
		return m.S
	}
	return ""
}

type DemoReq struct {
	D                    *Demo    `protobuf:"bytes,1,opt,name=d,proto3" json:"d,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DemoReq) Reset()         { *m = DemoReq{} }
func (m *DemoReq) String() string { return proto.CompactTextString(m) }
func (*DemoReq) ProtoMessage()    {}
func (*DemoReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_demo_6f9e178caa5c9b6a, []int{1}
}
func (m *DemoReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DemoReq.Unmarshal(m, b)
}
func (m *DemoReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DemoReq.Marshal(b, m, deterministic)
}
func (dst *DemoReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DemoReq.Merge(dst, src)
}
func (m *DemoReq) XXX_Size() int {
	return xxx_messageInfo_DemoReq.Size(m)
}
func (m *DemoReq) XXX_DiscardUnknown() {
	xxx_messageInfo_DemoReq.DiscardUnknown(m)
}

var xxx_messageInfo_DemoReq proto.InternalMessageInfo

func (m *DemoReq) GetD() *Demo {
	if m != nil {
		return m.D
	}
	return nil
}

type DemoRes struct {
	Res                  string   `protobuf:"bytes,1,opt,name=res,proto3" json:"res,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DemoRes) Reset()         { *m = DemoRes{} }
func (m *DemoRes) String() string { return proto.CompactTextString(m) }
func (*DemoRes) ProtoMessage()    {}
func (*DemoRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_demo_6f9e178caa5c9b6a, []int{2}
}
func (m *DemoRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DemoRes.Unmarshal(m, b)
}
func (m *DemoRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DemoRes.Marshal(b, m, deterministic)
}
func (dst *DemoRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DemoRes.Merge(dst, src)
}
func (m *DemoRes) XXX_Size() int {
	return xxx_messageInfo_DemoRes.Size(m)
}
func (m *DemoRes) XXX_DiscardUnknown() {
	xxx_messageInfo_DemoRes.DiscardUnknown(m)
}

var xxx_messageInfo_DemoRes proto.InternalMessageInfo

func (m *DemoRes) GetRes() string {
	if m != nil {
		return m.Res
	}
	return ""
}

func init() {
	proto.RegisterType((*Demo)(nil), "Demo")
	proto.RegisterType((*DemoReq)(nil), "DemoReq")
	proto.RegisterType((*DemoRes)(nil), "DemoRes")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// DemoServiceClient is the client API for DemoService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DemoServiceClient interface {
	Echo(ctx context.Context, in *DemoReq, opts ...grpc.CallOption) (*DemoRes, error)
}

type demoServiceClient struct {
	cc *grpc.ClientConn
}

func NewDemoServiceClient(cc *grpc.ClientConn) DemoServiceClient {
	return &demoServiceClient{cc}
}

func (c *demoServiceClient) Echo(ctx context.Context, in *DemoReq, opts ...grpc.CallOption) (*DemoRes, error) {
	out := new(DemoRes)
	err := c.cc.Invoke(ctx, "/DemoService/Echo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DemoServiceServer is the server API for DemoService service.
type DemoServiceServer interface {
	Echo(context.Context, *DemoReq) (*DemoRes, error)
}

func RegisterDemoServiceServer(s *grpc.Server, srv DemoServiceServer) {
	s.RegisterService(&_DemoService_serviceDesc, srv)
}

func _DemoService_Echo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DemoReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DemoServiceServer).Echo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/DemoService/Echo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DemoServiceServer).Echo(ctx, req.(*DemoReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _DemoService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "DemoService",
	HandlerType: (*DemoServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Echo",
			Handler:    _DemoService_Echo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "demo.proto",
}

func init() { proto.RegisterFile("demo.proto", fileDescriptor_demo_6f9e178caa5c9b6a) }

var fileDescriptor_demo_6f9e178caa5c9b6a = []byte{
	// 199 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4a, 0x49, 0xcd, 0xcd,
	0xd7, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x97, 0x72, 0x4e, 0xcf, 0x2c, 0xc9, 0x28, 0x4d, 0xd2, 0x4b,
	0xce, 0xcf, 0xd5, 0x4f, 0x2c, 0xc9, 0x2f, 0x4a, 0x4f, 0xac, 0x4c, 0x2d, 0xd3, 0x07, 0xcb, 0x25,
	0xeb, 0xa6, 0xa7, 0xe6, 0xe9, 0x16, 0x14, 0xa5, 0x16, 0x14, 0xe5, 0x27, 0xa7, 0x16, 0x17, 0xeb,
	0xe7, 0x17, 0x94, 0x64, 0xe6, 0xe7, 0x15, 0xeb, 0x23, 0x84, 0x20, 0x86, 0x28, 0xc9, 0x71, 0xb1,
	0xb8, 0xa4, 0xe6, 0xe6, 0x0b, 0x89, 0x71, 0x31, 0x16, 0x4b, 0x30, 0x2a, 0x30, 0x6a, 0x70, 0x3a,
	0x71, 0xec, 0xda, 0xc6, 0xca, 0xc2, 0xc5, 0xc4, 0xc1, 0x18, 0xc4, 0x58, 0xac, 0x24, 0xc7, 0xc5,
	0x0e, 0x92, 0x0f, 0x4a, 0x2d, 0x14, 0x12, 0xe6, 0x62, 0x4c, 0x01, 0x2b, 0xe1, 0x36, 0x62, 0xd5,
	0x03, 0x0b, 0x32, 0xa6, 0x28, 0x49, 0xc3, 0xe4, 0x8b, 0x85, 0x04, 0xb8, 0x98, 0x8b, 0x52, 0xa1,
	0x86, 0x04, 0x81, 0x98, 0x46, 0xda, 0x5c, 0xdc, 0x20, 0xc9, 0xe0, 0xd4, 0xa2, 0xb2, 0xcc, 0xe4,
	0x54, 0x21, 0x19, 0x2e, 0x16, 0xd7, 0xe4, 0x8c, 0x7c, 0x21, 0x0e, 0x3d, 0xa8, 0x91, 0x52, 0x30,
	0x56, 0xb1, 0x12, 0x43, 0x12, 0x1b, 0xd8, 0x41, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0x2a,
	0x94, 0xa2, 0x29, 0xe3, 0x00, 0x00, 0x00,
}
