// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: demo.proto

package proto

import strings "strings"
import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/infobloxopen/protoc-gen-preprocess/options"
import _ "google.golang.org/genproto/googleapis/api/annotations"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

func (m *Demo) Preprocess() error {

	m.PreprocessedField = strings.TrimSpace(m.PreprocessedField)
	m.PreprocessedField = strings.ToLower(m.PreprocessedField)

	for i, s := range m.PreprocessedRepeatedField {
		m.PreprocessedRepeatedField[i] = strings.TrimSpace(s)
		m.PreprocessedRepeatedField[i] = strings.ToUpper(s)
	}

	return nil
}

func (m *BackwardCompatible) Preprocess() error {

	m.Compatible = strings.TrimSpace(m.Compatible)

	return nil
}
